imu0:
  T_i_b:
  - [1.0, 0.0, 0.0, 0.0]
  - [0.0, 1.0, 0.0, 0.0]
  - [0.0, 0.0, 1.0, 0.0]
  - [0.0, 0.0, 0.0, 1.0]
  accelerometer_noise_density: 0.05
  accelerometer_random_walk: 0.001
  gyroscope_noise_density: 0.02
  gyroscope_random_walk: 4.0e-05
  model: calibrated
  rostopic: /mavros/imu/data
  time_offset: 0.0
  update_rate: 190.0
